### ISSUE TITLE
Build fails due to OpenSSL and database configuration issues

### ISSUE THREAD

**Issue by Ashutoshsingh123** [xmlsec/python-xmlsec#261]
While trying to set up the PostHog locally, I encountered a series of issues related to OpenSSL and the database configuration. 

Here is a brief description of what happened:

1. After resolving a few package-related issues, I ran into an error related to OpenSSL. The error message was:

```
Error: Configuration property "enable.ssl.certificate.verification" not supported in this build: OpenSSL not available at build time
   at HighLevelProducer.Client (/path/to/plugin-server/node_modules/.pnpm/node-rdkafka-acosom@2.16.1_ts-node@10.9.1_typescript@4.9.5/node_modules/node-rdkafka-acosom/lib/client.js:54:18)
   at HighLevelProducer.Producer (/path/to/plugin-server/node_modules/.pnpm/node-rdkafka-acosom@2.16.1_ts-node@10.9.1_typescript@4.9.5/node_modules/node-rdkafka-acosom/lib/producer.js:75:10)
   at new HighLevelProducer (/path/to/plugin-server/node_modules/.pnpm/node-rdkafka-acosom@2.16.1_ts-node@10.9.1_typescript@4.9.5/node_modules/node-rdkafka-acosom/lib/producer/high-level-producer.js:93:12)
   at createKafkaProducer (/path/to/plugin-server/src/kafka/producer.ts:16:22)
   at createHub (/path/to/plugin-server/src/utils/db/hub.ts:130:47)
   at processTicksAndRejections (node:internal/process/task_queues:95:5)
   at startPluginsServer (/path/to/plugin-server/src/main/pluginsServer.ts:232:56)
```
 
I've tried re-installing rdkafka and OpenSSL - found [this thread](https://github.com/xmlsec/python-xmlsec/issues/254) which helped me install OpenSSL without errors but I'm not sure if it completely fixed the root cause as I'm still facing the same issue.

2. Lastly, I encountered an error related to a missing database table `graphile_worker.jobs`. The error message was:

   ```
   psycopg2.errors.UndefinedTable: relation "graphile_worker.jobs" does not exist
   ```

I tried to troubleshoot this, but I'm not certain whether it's due to missing database migrations, a misconfiguration, or some other reason. 

Can someone please help? TIA.

**Comment by daibhin** [comment]
Hey 👋 

I ran into this exact same issue today. Eventually solved it (with the help of @benjackwhite)

Make sure you have these ENV variables set in your `.zshrc` (or equivalent) file:
```
export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"
```

Then purge the `node_modules` in your `plugin-server` and re-install them without the cache:
```
(env) ➜  posthog git:(master) cd plugin-server && rm -rf node_modules/ && cd ..
(env) ➜  posthog git:(master) pnpm i --force --dir plugin-server
```

You should see Kafka running an install script
```
node_modules/.pnpm/node-rdkafka-acosom@2.16.1_ts-node@10.9.1_typescript@4.9.5/node_modules/node-rdkafka-acosom: Running install script
```

**Comment by xrdt** [comment]
I had to also rebuild rdkafka in the plugin-server directory. 

`cd plugin-server && pnpm rebuild node-rdkafka`
